repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - pandas-stubs
  - repo: local
    hooks:
      - id: clean-after-commit
        name: Clean project environment after commit
        entry: make clean-all
        language: system
        always_run: true
        pass_filenames: false
        stages: [post-commit]
